# Generated by Django 4.0.3 on 2022-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_exam_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='A',
        ),
        migrations.RemoveField(
            model_name='question',
            name='B',
        ),
        migrations.RemoveField(
            model_name='question',
            name='C',
        ),
        migrations.RemoveField(
            model_name='question',
            name='D',
        ),
        migrations.RemoveField(
            model_name='question',
            name='t_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(limit_choices_to=4, related_name='choice+', to='questions.choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='t_answer',
            field=models.ManyToManyField(limit_choices_to=1, related_name='true_answer+', to='questions.choice'),
        ),
    ]
