# Generated by Django 4.0.3 on 2022-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_choice_remove_question_a_remove_question_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(related_name='choice+', to='questions.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='t_answer',
            field=models.ManyToManyField(related_name='true_answer+', to='questions.choice'),
        ),
    ]
