# Generated by Django 4.0.3 on 2022-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_choice_alter_question_t_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice',
        ),
        migrations.AddField(
            model_name='question',
            name='A',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='B',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='C',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='D',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='question',
            name='t_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='t_answer',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
