# Generated by Django 4.0.3 on 2022-04-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_question_choice_question_a_question_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='A_arabic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='B_arabic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='C_arabic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='D_arabic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_arabic',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
