# Generated by Django 4.0.3 on 2022-04-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_active',
            new_name='active',
        ),
    ]
