# Generated by Django 4.0.3 on 2022-04-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_rename_is_active_users_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='active',
        ),
    ]
