# Generated by Django 4.0.3 on 2022-04-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
