# Generated by Django 4.0.3 on 2022-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_remove_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('slide_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slideshow', models.ImageField(upload_to='static/img/slide/')),
                ('slideshow_mob', models.ImageField(upload_to='static/img/slide/mob/')),
            ],
        ),
    ]
