# Generated by Django 4.0.3 on 2022-04-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_slideshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='slideshow_mob',
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='slideshow',
            field=models.ImageField(upload_to='media/img/slide/'),
        ),
    ]
