# Generated by Django 4.0.3 on 2022-04-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_remove_slideshow_slideshow_mob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='slideshow',
            field=models.ImageField(upload_to='img/slide/'),
        ),
    ]
